### PR TITLE
Add prettier to the project

### LINKED ISSUE #8: [Feature] Add prettier
**Is your feature request related to a problem? Please describe.**
It would be nice to have formatter with well-defined rules so we don't have to worry about what tools others use to format their code.

**Describe the solution you'd like**
Add prettier to the project

### PR DESCRIPTION
**Pull request by seog-jun**
Fixes #8 

Hi, I created the PR to add `Prettier` to the project and added `Husky` and `pretty-quick` to apply `Prettier` automatically when you make git commits. Also, I updated scripts in package.json to add 2 commands: `format` and `check-format`, you can use the commands manually. 

Let me know if there are files that you don't want to apply `Prettier`, and I can update `.prettierignore` file, it depends on your preference. Thanks

### CODE REVIEW

**Comment by seog-jun** [comment]
Can you please add the `hacktoberfest` label to this ticket? I'd appreciate that!

**Review by eduardconstantin — CHANGES_REQUESTED** [review]
This looks nice!
One small request, could you make the tabs shorter?

**Comment by seog-jun** [comment]
The current tabWidth is set to `4`, do you want to make it `2`?

**Comment by eduardconstantin** [comment]
> The current tabWidth is set to `4`, do you want to make it `2`?

Yes, please!

**Review by eduardconstantin — APPROVED** [review]
Much better! Thank you!

**Pull request merged**
