### PR TITLE
[Feature] Allow User To Toggle between light/dark mode

### PR DESCRIPTION
**Pull request by KriteshTimsina**
Implemented Dark/Light Mode toggle button.

Features:
- can toggle between dark and light mode
- persist selected mode

Additional Libraries
- next-themes (for toggling  and persisting modes )
- react-icons (for dark and light mode icons)

Screenshots
image
image

### CODE REVIEW

**Comment by eduardconstantin** [comment]
This looks nice! But I think the buttons should be inverted - when is dark it should be sun and when is light it should be moon
Also could you move the button next to github stars button? And make it a bit smaller.

**Comment by KriteshTimsina** [comment]
Got it !

**Comment by KriteshTimsina** [comment]
Issue #15 changes:
- Show dark mode icon in light mode and vice-versa
- positioned darkmode switch next to github icon
- fixed switch not working on first click

**Review by eduardconstantin — APPROVED** [review]
Thank you for your contribution!

**Pull request merged**
